export const START_MINING_REQUEST = "START_MINNING_REQUEST";
export const START_MINING_SUCCESS = "START_MINNING_SUCCESS";
export const START_MINING_FAIL = "START_MINNINGORD_FAIL";
export const START_MINING_RESET = "START_MINING_RESET";

export const GET_MINED_COINS = "GET_MINED_COINS";
export const RESET_MINED_COINS = "RESET_MINED_COINS";

export const REWARDS_REQUEST = "REWARDS_REQUEST";
export const REWARDS_SUCCESS = "REWARDS_SUCCESS";
export const REWARDS_FAIL = "REWARDS_FAIL";
export const REWARDS_RESET = "REWARDS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
