export const WITHDRAW_REQUEST = "WITHDRAW_REQUEST";
export const WITHDRAW_SUCCESS = "WITHDRAW_SUCCESS";
export const WITHDRAW_FAIL = "WITHDRAW_FAIL";
export const WITHDRAW_RESET = "WITHDRAW_RESET";


export const GET_WITHDRAW_REQUEST = "GET_WITHDRAW_REQUEST";
export const GET_WITHDRAW_SUCCESS = "GET_WITHDRAW_SUCCESS";
export const GET_WITHDRAW_FAIL = "GET_WITHDRAW_FAIL";
export const GET_WITHDRAW_RESET = "GET_WITHDRAW_RESET";

export const GET_CRYPTO_REQUEST = "GET_CRYPTO_REQUEST";
export const GET_CRYPTO_SUCCESS = "GET_CRYPTO_SUCCESS";
export const GET_CRYPTO_FAIL = "GET_CRYPTO_FAIL";
export const GET_CRYPTO_RESET = "GET_CRYPTO_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";